USE MASTER;
DROP DATABASE IF EXISTS BEEKEY;

CREATE DATABASE BEEKEY;
USE BEEKEY;

CREATE TABLE ACCOUNT(
	USERNAME VARCHAR(30),
	PASSWORD CHAR(64),
	TYPE INT,
	GENDER BOOLEAN,
	PHONE VARCHAR(12),
	ADDRESS VARCHAR(30),
	COIN INT,
	
	PRIMARY KEY(USERNAME)
);

CREATE TABLE CATEGORY(
	CATEGORY_ID INT AUTO_INCREMENT,
	CATEGORY_NAME VARCHAR(30),

	PRIMARY KEY(CATEGORY_ID)
);

CREATE TABLE TASK(
	TASK_ID INT AUTO_INCREMENT,
	DESCRIPTION TEXT,
	OFFER INT,
	DEADLINE DATETIME,
	CATEGORY_ID INT,
	LANCER_ID VARCHAR(30),
	USER_ID VARCHAR(30),

	PRIMARY KEY(TASK_ID),
	FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),
	FOREIGN KEY(LANCER_ID) REFERENCES ACCOUNT(USERNAME),
	FOREIGN KEY(USER_ID) REFERENCES ACCOUNT(USERNAME)
);

CREATE TABLE FEEDBACK(
	FEEDBACK_ID INT AUTO_INCREMENT,
	DESCRIPTION TEXT,
	STAR INT,
	LANCER_ID VARCHAR(30),
	USER_ID VARCHAR(30),
	TASK_ID INT,
	
	PRIMARY KEY(FEEDBACK_ID),
	FOREIGN KEY(USER_ID) REFERENCES ACCOUNT(USERNAME),
	FOREIGN KEY(LANCER_ID) REFERENCES ACCOUNT(USERNAME),
	FOREIGN KEY(TASK_ID) REFERENCES ACCOUNT(TASK_ID)
);

CREATE TABLE COUNTER_OFFER(
	TASK_ID INT,
	LANCER_ID VARCHAR(30),
	OFFER INT,
	REASON TEXT,

	PRIMARY KEY(TASK_ID,LANCER_ID),
	FOREIGN KEY(TASK_ID) REFERENCES TASK(TASK_ID),
	FOREIGN KEY(LANCER_ID) REFERENCES ACCOUNT(USERNAME)
);

CREATE TABLE CHAT(
	SEND_ID VARCHAR(30),
	RECEIVE_ID VARCHAR(30),
	DATE_TIME DATETIME,
	CONTENT TEXT,

	PRIMARY KEY(SEND_ID,RECEIVE_ID,DATE_TIME),
	FOREIGN KEY(SEND_ID) REFERENCES ACCOUNT(USERNAME),
	FOREIGN KEY(RECEIVE_ID) REFERENCES ACCOUNT(USERNAME)
);

CREATE TABLE ATTACH_FILE(
	TASK_ID INT,
	FILE_PATH VARCHAR(500),

	PRIMARY KEY(TASK_ID,FILE_PATH),
	FOREIGN KEY(TASK_ID) REFERENCES TASK(TASK_ID)
);

--------------------------------------------------------------------

INSERT INTO ACCOUNT(USERNAME,PASSWORD,TYPE) VALUES
("admin","8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",1);

INSERT INTO CATEGORY(CATEGORY_NAME) VALUES
("Testing"),
("Mobile application"),
("Desktop application"),
("Web application"),
("Cyber security"),
("Data analysis");
